language: java
deploy:
  provider: heroku
  api_key:
    secure: cSKZjSBUN74m7SxySc1tYlJ3RquIzak1O0i/0F27JenFhxbL1BNmV2m2UrzySwBddC8jRa1lnBv7Gv06iwLKqoSTDbykLUpcFkqzgW/B6DgkE3HAG6vK1k3BKAhuA+pa8hzj2slEZS28Y67V0A73Y33r0ds/vAxRZ2lWGslo4yRVhwCbR7iWC6lJ2kxgJqep1yrB8jQOTJaj8bxyqNJvAW3SzbqIDauQNIsktHvYS/gxFKqjprXeDLTy/oGmKz6coEBjpt+dQZ1ExY476dLC6FUSi3HXj8d9Nw7N+ac9id7yE1eAo2ywdJWgkFs7eZGnaWDqbEydjH+FfQ9p9DPnm5sSC673gRzfsA9nwv3uPw/cYtVMeknc8NHCPArIe1gVYYrzgwHN5NmHeLFdnG40kdmJUyaFhdb4FA3wROs4Yknw9krVj7VhYQvgfMB8zaTNF/ph3jZ7m9JARO4O78QTBX0wpBtoVneFPifcciHLsuOpgIMmdUxYg00Se1+Ny8rosuaWI02QvryNA5XeOfn9SermYq+9p9Hcq0L5sU8KoIw5QZiAzLWsKiPIaKq8GwxRtf5s7TOc9+l+Vt1TIk+FGNluBVSsVq3zeRdyCxTyWCe8FAy4hMkx7pyXRzjh67YsHnVHgtTzsqTHY7Te7dytfliydJaxCv488hJty+Dhn4k=
  app: whispering-woodland
